// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMkphHEhslpqPD8GLAMfaYQHqX31nUs68',
    appId: '1:662402741570:web:16c2f441585ad3a92984db',
    messagingSenderId: '662402741570',
    projectId: 'voiture-e5b44',
    authDomain: 'voiture-e5b44.firebaseapp.com',
    storageBucket: 'voiture-e5b44.appspot.com',
    measurementId: 'G-0SRX3XC9P9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVRl2mvgNBGG3JM3WkklRtfpybdKl8oJo',
    appId: '1:662402741570:android:c10027b75e52a7bd2984db',
    messagingSenderId: '662402741570',
    projectId: 'voiture-e5b44',
    storageBucket: 'voiture-e5b44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoAFyWICCrE6tw9sjfX5PSxcPDmOqCw38',
    appId: '1:662402741570:ios:e3f246454d9743ae2984db',
    messagingSenderId: '662402741570',
    projectId: 'voiture-e5b44',
    storageBucket: 'voiture-e5b44.appspot.com',
    iosBundleId: 'com.example.voiture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoAFyWICCrE6tw9sjfX5PSxcPDmOqCw38',
    appId: '1:662402741570:ios:45d876505238086b2984db',
    messagingSenderId: '662402741570',
    projectId: 'voiture-e5b44',
    storageBucket: 'voiture-e5b44.appspot.com',
    iosBundleId: 'com.example.voiture.RunnerTests',
  );
}
